# Generated by Django 5.1.1 on 2024-12-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="", max_length=1024, verbose_name="content"
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="time")),
            ],
            options={
                "db_table": "comment",
                "ordering": ["time"],
            },
        ),
    ]
