# Generated by Django 5.1.1 on 2024-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(default="", verbose_name="content"),
        ),
    ]
