# Generated by Django 5.1.1 on 2024-10-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="motto",
            field=models.CharField(
                default="这个人很懒，什么都没有留下", max_length=256, verbose_name="motto"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=256, verbose_name="password"),
        ),
    ]
