# Generated by Django 5.1.1 on 2024-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
        ("classes", "0001_initial"),
        ("message", "0001_initial"),
        ("tag", "0001_initial"),
        ("task", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="charge_classes",
            field=models.ManyToManyField(
                blank=True, related_name="user_charge_classes", to="classes.class"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="create_activities",
            field=models.ManyToManyField(
                related_name="user_create_activities", to="activity.activity"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("secret", "不设置/保密"), ("male", "男"), ("female", "女")],
                default="保密",
                max_length=32,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="identity",
            field=models.CharField(
                choices=[("student", "学生"), ("teacher", "老师"), ("root", "管理员")],
                default="学生",
                max_length=32,
                verbose_name="身份",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="in_classes",
            field=models.ManyToManyField(
                blank=True, related_name="user_in_classes", to="classes.class"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="participate_activities",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_participate_activities",
                to="activity.activity",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="readed_messages",
            field=models.ManyToManyField(
                blank=True, related_name="user_readed_messages", to="message.message"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="send_messages",
            field=models.ManyToManyField(
                blank=True, related_name="user_send_messages", to="message.message"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="user_tags", to="tag.tag"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, related_name="user_tasks", to="task.task"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unread_messages",
            field=models.ManyToManyField(
                blank=True, related_name="user_unread_messages", to="message.message"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=256, verbose_name="密码"),
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
