# Generated by Django 5.1.1 on 2024-12-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preference",
            field=models.JSONField(default=dict, verbose_name="preference"),
        ),
    ]
