# Generated by Django 5.1.1 on 2024-10-21 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_user_charge_classes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="charge_classes",
        ),
        migrations.RemoveField(
            model_name="user",
            name="create_activities",
        ),
        migrations.RemoveField(
            model_name="user",
            name="in_classes",
        ),
        migrations.RemoveField(
            model_name="user",
            name="participate_activities",
        ),
        migrations.RemoveField(
            model_name="user",
            name="readed_messages",
        ),
        migrations.RemoveField(
            model_name="user",
            name="send_messages",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tasks",
        ),
        migrations.RemoveField(
            model_name="user",
            name="unread_messages",
        ),
    ]
