# Generated by Django 5.1.1 on 2024-11-17 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_phone"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
