# Generated by Django 5.1.1 on 2024-10-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_tag_name"),
        ("users", "0003_remove_user_charge_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(
                related_name="tasks_owners", to="tag.tag", verbose_name="own_tags"
            ),
        ),
    ]
