# Generated by Django 5.1.1 on 2024-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="手机号还未定义", max_length=32, verbose_name="phone"
            ),
        ),
    ]
