# Generated by Django 5.1.1 on 2024-11-17 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
