# Generated by Django 5.1.1 on 2024-10-25 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isDelete",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AuthRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("login_at", models.DateTimeField()),
                ("expires_by", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
