# Generated by Django 5.1.1 on 2024-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_isdelete_authrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tags",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatar/default.png", upload_to="avatar/", verbose_name="avatar"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="motto",
            field=models.CharField(
                default="这个人很懒，什么都没有留下", max_length=256, verbose_name="个性签名"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="保密", max_length=32, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "该邮箱已被注册"},
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("secret", "不设置/保密"), ("male", "男"), ("female", "女")],
                default="保密",
                max_length=32,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="identity",
            field=models.CharField(
                choices=[("student", "学生"), ("teacher", "老师"), ("root", "管理员")],
                default="学生",
                max_length=32,
                verbose_name="identity",
            ),
        ),
    ]
