# Generated by Django 5.1.1 on 2024-11-23 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
