# Generated by Django 5.1.1 on 2024-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="邮箱还未定义",
                error_messages={"unique": "该邮箱已被注册"},
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="identity",
            field=models.IntegerField(
                choices=[(0, "管理员"), (1, "教师"), (2, "学生")],
                default=2,
                max_length=32,
                verbose_name="identity",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="手机号还未定义", max_length=32, verbose_name="phone"
            ),
        ),
    ]
