# Generated by Django 5.1.1 on 2024-11-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_email_alter_user_identity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identity",
            field=models.IntegerField(
                choices=[(0, "管理员"), (1, "教师"), (2, "学生")],
                default=2,
                verbose_name="identity",
            ),
        ),
    ]
