# Generated by Django 5.1.1 on 2024-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "title",
                    models.CharField(
                        default="活动标题", max_length=256, verbose_name="title"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="活动描述", max_length=1024, verbose_name="content"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        default="活动地点", max_length=1024, verbose_name="place"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="start_time"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end_time"
                    ),
                ),
            ],
            options={
                "db_table": "activity",
            },
        ),
        migrations.CreateModel(
            name="ActivityUserRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="任务名", max_length=256, verbose_name="aliasName"
                    ),
                ),
                (
                    "permission",
                    models.IntegerField(
                        choices=[(0, "创建"), (1, "参与")],
                        default=0,
                        verbose_name="permission",
                    ),
                ),
            ],
            options={
                "db_table": "activity_user_relationship",
            },
        ),
    ]
