# Generated by Django 5.1.1 on 2024-12-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0001_initial"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="comment_activities",
                to="comment.comment",
                verbose_name="activity_comment",
            ),
        ),
    ]
