# Generated by Django 5.1.1 on 2024-10-21 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
        ("tag", "0002_tag_name"),
        ("users", "0004_user_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="content",
            field=models.CharField(
                default="活动描述", max_length=1024, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end_time"),
        ),
        migrations.AddField(
            model_name="activity",
            name="owners",
            field=models.ManyToManyField(
                related_name="activities_own",
                to="users.user",
                verbose_name="activity_owners",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="participants",
            field=models.ManyToManyField(
                related_name="activities_in",
                to="users.user",
                verbose_name="activity_participants",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="place",
            field=models.CharField(
                default="活动地点", max_length=1024, verbose_name="place"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="start_time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="tags",
            field=models.ManyToManyField(
                related_name="activities_have_tag",
                to="tag.tag",
                verbose_name="activity_tag",
            ),
        ),
    ]
