# Generated by Django 5.1.1 on 2024-11-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="tags",
            field=models.ManyToManyField(
                related_name="tag_activities", to="tag.tag", verbose_name="activity_tag"
            ),
        ),
        migrations.AddField(
            model_name="activityuserrelationship",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship",
                to="activity.activity",
                verbose_name="activity_ponit",
            ),
        ),
    ]
