# Generated by Django 5.1.1 on 2024-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0001_initial"),
        ("tag", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="owners",
            field=models.ManyToManyField(
                related_name="activities_own",
                to="users.user",
                verbose_name="activity_owners",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="participants",
            field=models.ManyToManyField(
                related_name="activities_in",
                to="users.user",
                verbose_name="activity_participants",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="tags",
            field=models.ManyToManyField(
                related_name="activities_have_tag",
                to="tag.tag",
                verbose_name="activity_tag",
            ),
        ),
    ]
