# Generated by Django 5.1.1 on 2024-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0002_initial"),
        ("tag", "0004_remove_tag_create_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="tags",
            field=models.ManyToManyField(
                related_name="tags", to="tag.tag", verbose_name="activity_tag"
            ),
        ),
    ]
