# Generated by Django 5.1.1 on 2024-11-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_alter_activity_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
