# Generated by Django 5.1.1 on 2024-11-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_initial"),
        ("tag", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="start_time",
            field=models.DateTimeField(verbose_name="start_time"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tag_activities",
                to="tag.tag",
                verbose_name="activity_tag",
            ),
        ),
    ]
