# Generated by Django 5.1.1 on 2024-11-24 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_activity_title_activityuserrelationship"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activityuserrelationship",
            old_name="task",
            new_name="activity",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="owners",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="participants",
        ),
    ]
