# Generated by Django 5.1.1 on 2024-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0006_rename_task_activityuserrelationship_activity_and_more"),
        ("tag", "0004_remove_tag_create_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="tags",
            field=models.ManyToManyField(
                related_name="tag_activities", to="tag.tag", verbose_name="activity_tag"
            ),
        ),
    ]
