# Generated by Django 5.1.1 on 2024-10-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(
                default="tag名", max_length=1024, verbose_name="tag_name"
            ),
        ),
    ]
