# Generated by Django 5.1.1 on 2024-10-25 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0002_tag_name"),
        ("users", "0006_remove_user_tags_user_avatar_user_motto_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="content",
            field=models.CharField(
                default="暂无tag描述", max_length=1024, verbose_name="tag_content"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="create_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_create",
                to="users.user",
                verbose_name="create_user",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                default="tag名", max_length=256, verbose_name="tag_name"
            ),
        ),
    ]
