# Generated by Django 5.1.1 on 2024-11-22 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0003_tag_color_tag_fixed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="create_user",
        ),
    ]
