# Generated by Django 5.1.1 on 2024-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="班级", max_length=256, verbose_name="title"
                    ),
                ),
                (
                    "introduction",
                    models.CharField(
                        default="暂时还没有班级介绍",
                        max_length=1024,
                        verbose_name="introduction",
                    ),
                ),
            ],
            options={
                "db_table": "classes",
            },
        ),
    ]
