# Generated by Django 5.1.1 on 2024-10-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
        ("task", "0004_remove_task_create_time_remove_task_overdue_time_and_more"),
        ("users", "0004_user_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="introduction",
            field=models.CharField(
                default="暂时还没有班级介绍", max_length=1024, verbose_name="class_intro"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                related_name="classes", to="users.user", verbose_name="class_students"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="tasks",
            field=models.ManyToManyField(
                related_name="shared_classes",
                to="task.task",
                verbose_name="class_tasks",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teachers",
            field=models.ManyToManyField(
                related_name="owned_classes",
                to="users.user",
                verbose_name="class_teachers",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="title",
            field=models.CharField(
                default="班级", max_length=1024, verbose_name="class_title"
            ),
        ),
    ]
