# Generated by Django 5.1.1 on 2024-11-25 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                related_name="classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="students",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="tasks",
            field=models.ManyToManyField(
                related_name="shared_classes", to="task.task", verbose_name="tasks"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teachers",
            field=models.ManyToManyField(
                related_name="owned_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="teachers",
            ),
        ),
    ]
