# Generated by Django 5.1.1 on 2024-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("task", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                related_name="classes", to="users.user", verbose_name="class_students"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="tasks",
            field=models.ManyToManyField(
                related_name="shared_classes",
                to="task.task",
                verbose_name="class_tasks",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teachers",
            field=models.ManyToManyField(
                related_name="owned_classes",
                to="users.user",
                verbose_name="class_teachers",
            ),
        ),
    ]
