# Generated by Django 5.1.1 on 2024-10-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_initial"),
        ("task", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="introduction",
            field=models.CharField(
                default="暂时还没有班级介绍", max_length=1024, verbose_name="introduction"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                related_name="classes", to="users.user", verbose_name="students"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="tasks",
            field=models.ManyToManyField(
                related_name="shared_classes", to="task.task", verbose_name="tasks"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="teachers",
            field=models.ManyToManyField(
                related_name="owned_classes", to="users.user", verbose_name="teachers"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="title",
            field=models.CharField(default="班级", max_length=1024, verbose_name="title"),
        ),
    ]
