# Generated by Django 5.1.1 on 2024-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="introduction",
            field=models.TextField(default="暂时还没有班级介绍", verbose_name="introduction"),
        ),
    ]
