# Generated by Django 5.1.1 on 2024-11-28 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0003_alter_class_tasks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="students",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="owned_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="teachers",
            ),
        ),
    ]
