# Generated by Django 5.1.1 on 2024-10-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0003_alter_class_introduction_alter_class_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="title",
            field=models.CharField(default="班级", max_length=256, verbose_name="title"),
        ),
    ]
