# Generated by Django 5.1.1 on 2024-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="活动", max_length=256, verbose_name="title"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="任务描述", max_length=1024, verbose_name="content"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="start_time"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end_time"
                    ),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
    ]
