# Generated by Django 5.1.1 on 2024-12-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="活动", max_length=256, verbose_name="title"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="任务描述", max_length=1024, verbose_name="content"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="start_time")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end_time"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="son_task",
                        to="task.task",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tag_tasks",
                        to="tag.tag",
                        verbose_name="task_tag",
                    ),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskUserRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="任务名", max_length=256, verbose_name="aliasName"
                    ),
                ),
                (
                    "percentage",
                    models.IntegerField(default=0, verbose_name="finish_percentage"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="is_finished"),
                ),
                (
                    "permission",
                    models.IntegerField(
                        choices=[(0, "创建"), (1, "参与")],
                        default=0,
                        verbose_name="permission",
                    ),
                ),
                (
                    "alarms",
                    models.ManyToManyField(
                        blank=True, to="task.alarm", verbose_name="alarms"
                    ),
                ),
            ],
            options={
                "db_table": "task_user_relationship",
            },
        ),
    ]
