# Generated by Django 5.1.1 on 2024-12-04 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tag", "0002_initial"),
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskuserrelationship",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_relationship",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskuserrelationship",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks_have_tag", to="tag.tag"
            ),
        ),
        migrations.AddField(
            model_name="taskuserrelationship",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship",
                to="task.task",
            ),
        ),
    ]
