# Generated by Django 5.1.1 on 2024-11-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateTimeField(verbose_name="start_time"),
        ),
    ]
