# Generated by Django 5.1.1 on 2024-12-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskuserrelationship",
            name="color",
            field=models.CharField(default="", max_length=64, verbose_name="color"),
        ),
    ]
