# Generated by Django 5.1.1 on 2024-10-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_remove_task_create_time_remove_task_overdue_time_and_more"),
        ("users", "0005_user_isdelete_authrecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="related_uses",
            new_name="related_users",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="task",
            name="create_users",
        ),
        migrations.AddField(
            model_name="task",
            name="create_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_create",
                to="users.user",
                verbose_name="create_user",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="son_task",
                to="task.task",
            ),
        ),
    ]
