# Generated by Django 5.1.1 on 2024-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_taskuserrelationship_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskuserrelationship",
            name="finish_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="finish_time"
            ),
        ),
    ]
