# Generated by Django 5.1.1 on 2024-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0003_tag_content_tag_create_user_alter_tag_name"),
        ("task", "0005_rename_related_uses_task_related_users_and_more"),
        ("users", "0006_remove_user_tags_user_avatar_user_motto_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="related_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks_related",
                to="users.user",
                verbose_name="related_users",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks_have_tag",
                to="tag.tag",
                verbose_name="task_tag",
            ),
        ),
    ]
