# Generated by Django 5.1.1 on 2024-12-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0005_taskuserrelationship_finish_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskuserrelationship",
            name="color",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="color"
            ),
        ),
    ]
