# Generated by Django 5.1.1 on 2024-11-24 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0004_remove_tag_create_user"),
        ("task", "0005_taskuserrelationship_percentage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskuserrelationship",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_relationship",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskuserrelationship",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks_have_tag", to="tag.tag"
            ),
        ),
    ]
