# Generated by Django 5.1.1 on 2024-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0007_task_tags_alter_taskuserrelationship_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="taskuserrelationship",
            name="alarms",
            field=models.ManyToManyField(to="task.alarm", verbose_name="alarms"),
        ),
    ]
