# Generated by Django 5.1.1 on 2024-11-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="email", max_length=256, verbose_name="title"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        default="信息内容", max_length=4096, verbose_name="content"
                    ),
                ),
                (
                    "send_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="send_time"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="is_read")),
            ],
            options={
                "db_table": "message",
            },
        ),
    ]
