# Generated by Django 5.1.1 on 2024-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(default="信息内容", verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(
                default="email", max_length=1024, verbose_name="title"
            ),
        ),
    ]
