# Generated by Django 5.1.1 on 2024-11-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0003_message_receive_user_message_send_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(
                default="信息内容", max_length=4096, verbose_name="content"
            ),
        ),
    ]
